on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1
      - run: make check
      - run: make delete
